DocWorks for wix-ui-santa - 63 changes detected, but 83 issue detected changes: Service $w.AddressInput has changed summary Service $w.AddressInput property filter has changed setter Service $w.AddressInput property filter has changed summary Service $w.AddressInput property filter has changed description Service $w.AddressInput property filter.examples[0] has changed title Service $w.AddressInput property filter.examples[0] has changed body Service $w.AddressInput property filter.examples[1] has changed title Service $w.AddressInput property filter.examples[1] has changed body Service $w.AddressInput property placeholder has changed setter Service $w.AddressInput property placeholder has changed description Service $w.AddressInput property placeholder.examples[0] has changed body Service $w.AddressInput property value has changed setter Service $w.AddressInput property value has changed description Service $w.AddressInput property value.examples[0] has changed body Service $w.AddressInput property value.examples[1] has changed body Service $w.AddressInput property value.examples has 2 new examples Service $w.AddressInput message Address member formatted has changed doc Service $w.AddressInput message Address member country has changed type Service $w.AddressInput message Address member postalCode has changed type Service $w.AddressInput message Address member streetNumber was removed Service $w.AddressInput message Address member route was removed Service $w.AddressInput message Address member locality was removed Service $w.AddressInput message Address member adminArea1 was removed Service $w.AddressInput message Address member adminArea2 was removed Service $w.AddressInput message Address has a new member streetAddress Service $w.AddressInput message Address has a new member city Service $w.AddressInput message Address has a new member subdivision Service $w.AddressInput message Address.examples[0] has changed body Service $w.AddressInput message Address.examples[1] has changed body Service $w.AddressInput message AddressAdminArea1 was removed Service $w.AddressInput message AddressAdminArea2 was removed Service $w.AddressInput message AddressBias was removed Service $w.AddressInput message AddressCountry was removed Service $w.AddressInput message AddressFilter member country has changed doc Service $w.AddressInput message AddressFilter member country has changed optional Service $w.AddressInput message AddressFilter has changed summary Service $w.AddressInput message AddressFilter has a new link [filter](#filter) Service $w.AddressInput message AddressFilter.examples[0] has changed title Service $w.AddressInput message AddressFilter.examples[0] has changed body Service $w.AddressInput message AddressFilter.examples has 1 new examples Service $w.AddressInput message AddressLocality was removed Service $w.AddressInput message AddressLocation has a new link [value](#value) Service $w.AddressInput message AddressLocation.examples[0] has changed body Service $w.AddressInput message AddressPostalCode was removed Service $w.AddressInput message AddressRoute was removed Service $w.AddressInput message AddressStreetNumber was removed Service $w.AddressInput has changed extra.queryable Service $w.CustomElement has changed description Service $w.CustomElement property seoMarkup has changed description Service $w.CustomElement property seoMarkup.examples[0] has changed body Service $w.CustomElement operation on has changed summary Service $w.CustomElement operation on.examples[0] has changed body Service $w.CustomElement operation setAttribute has changed param value type Service $w.CustomElement operation setAttribute has changed summary Service $w.CustomElement operation setAttribute.examples[0] has changed body Service $w.VideoPlayer operation mute.examples has 1 new examples Service $w.VideoPlayer operation pause.examples has 1 new examples Service $w.VideoPlayer operation play.examples has 1 new examples Service $w.VideoPlayer operation seek.examples has 1 new examples Service $w.VideoPlayer operation stop has changed description Service $w.VideoPlayer operation stop.examples has 1 new examples Service $w.VideoPlayer operation togglePlay.examples has 1 new examples Service $w.VideoPlayer operation unmute.examples has 1 new examples
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (37))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (612))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (651))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (690))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (727))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (26))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (62))
Mixin $w.DisabledMixin not found (AddressInput.js (62))
Mixin $w.RequiredMixin not found (AddressInput.js (62))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (62))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (62))
Mixin $w.FocusMixin not found (AddressInput.js (62))
Mixin $w.ClickableMixin not found (AddressInput.js (62))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (587))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (626))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (665))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (702))
Mixin $w.Element not found (MusicPlayer.js (9))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (9))
Operation onError has an unknown param type $w.EventHandler (Captcha.js (28))
Operation onError has an unknown return type $w.captcha (Captcha.js (28))
Operation onTimeout has an unknown param type $w.EventHandler (Captcha.js (52))
Operation onTimeout has an unknown return type $w.captcha (Captcha.js (52))
Operation onVerified has an unknown param type $w.EventHandler (Captcha.js (80))
Operation onVerified has an unknown return type $w.captcha (Captcha.js (80))
Property style has an unknown type $w.Style (ProgressBar.js (42))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
Mixin $w.Element not found (CustomElement.js (5))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (5))
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_get.es6' not found. File: VideoPlayer.js line: 511
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_set.es6' not found. File: VideoPlayer.js line: 511
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/Captcha-onTimeout.es6' not found. File: Captcha.js line: 93