DocWorks for wix-ui-santa - 1 change detected, but 96 issue detected changes: Service $w.SelectionTags has changed description
issues:
Property style has an unknown type $w.Style (SelectionTagsList.js (211))
Property selectedIndices is a write only property (SelectionTagsList.js (144))
Property value is a write only property (SelectionTagsList.js (189))
Mixin $w.FormElement not found (SelectionTagsList.js (38))
Mixin $w.HiddenCollapsedMixin not found (SelectionTagsList.js (38))
Mixin $w.DisabledMixin not found (SelectionTagsList.js (38))
Mixin $w.FocusMixin not found (SelectionTagsList.js (38))
Mixin $w.StyleMixin not found (SelectionTagsList.js (38))
Mixin $w.RequiredMixin not found (SelectionTagsList.js (38))
Operation setAttribute is defined two or more times (CustomElement.js (53, 53))
Operation on is defined two or more times (CustomElement.js (77, 77))
Property seoMarkup is defined two or more times (CustomElement.js (107, 107))
Mixin $w.Element not found (CustomElement.js (5))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (5))
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (37))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (612))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (651))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (690))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (727))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (26))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (62))
Mixin $w.DisabledMixin not found (AddressInput.js (62))
Mixin $w.RequiredMixin not found (AddressInput.js (62))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (62))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (62))
Mixin $w.FocusMixin not found (AddressInput.js (62))
Mixin $w.ClickableMixin not found (AddressInput.js (62))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (587))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (626))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (665))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (702))
Mixin $w.Element not found (MusicPlayer.js (9))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (9))
Mixin $w.Element not found (Captcha.js (8))
Mixin $w.FocusMixin not found (Captcha.js (8))
Mixin $w.HiddenCollapsedMixin not found (Captcha.js (8))
Property style has an unknown type $w.Style (ProgressBar.js (42))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
Operation setAttribute is defined two or more times (CustomElement.js (53, 53))
Operation on is defined two or more times (CustomElement.js (77, 77))
Property seoMarkup is defined two or more times (CustomElement.js (107, 107))
Mixin $w.Element not found (CustomElement.js (5))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (5))
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_get.es6' not found. File: VideoPlayer.js line: 511
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_set.es6' not found. File: VideoPlayer.js line: 511
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 711