DocWorks for wix-ui-santa - 54 changes detected, but 79 issue detected changes: Service $w.Captcha has a new mixes $w.Element Service $w.Captcha has a new mixes $w.FocusMixin Service $w.Captcha has a new mixes $w.HiddenCollapsedMixin Service $w.Captcha has changed summary Service $w.Captcha has changed description Service $w.Captcha property token has changed description Service $w.Captcha property token.examples[0] has changed title Service $w.Captcha property token.examples[1] has changed title Service $w.Captcha property token.examples[1] has changed body Service $w.Captcha property token.examples[1] has changed extra.description Service $w.Captcha operation onError has changed param name from cb to handler Service $w.Captcha operation onError has changed param handler type Service $w.Captcha operation onError has changed param handler doc Service $w.Captcha operation onError has changed return type Service $w.Captcha operation onError has changed return doc Service $w.Captcha operation onError has changed summary Service $w.Captcha operation onError has changed description Service $w.Captcha operation onError link [onError( )](#onError) was removed Service $w.Captcha operation onError.examples has 1 new examples Service $w.Captcha operation onTimeout has changed param name from cb to handler Service $w.Captcha operation onTimeout has changed param handler type Service $w.Captcha operation onTimeout has changed param handler doc Service $w.Captcha operation onTimeout has changed return type Service $w.Captcha operation onTimeout has changed return doc Service $w.Captcha operation onTimeout has changed summary Service $w.Captcha operation onTimeout has changed description Service $w.Captcha operation onTimeout link [onTimeout( )](#onTimeout) was removed Service $w.Captcha operation onTimeout.examples has 1 new examples Service $w.Captcha operation onVerified has changed param name from cb to handler Service $w.Captcha operation onVerified has changed param handler type Service $w.Captcha operation onVerified has changed param handler doc Service $w.Captcha operation onVerified has changed return type Service $w.Captcha operation onVerified has changed return doc Service $w.Captcha operation onVerified has changed summary Service $w.Captcha operation onVerified has changed description Service $w.Captcha operation onVerified link [onVerified( )](#onVerified) was removed Service $w.Captcha operation onVerified.examples has 2 new examples Service $w.Captcha operation reset has changed return doc Service $w.Captcha operation reset has changed summary Service $w.Captcha operation reset has changed description Service $w.Captcha operation reset.examples[1] has changed title Service $w.Captcha operation reset.examples[1] has changed body Service $w.Captcha operation reset.examples[1] has changed extra.description Service $w.Captcha has changed extra.notes Service $w.Captcha has changed extra.queryable Service $w.CustomElement has changed description Service $w.CustomElement property seoMarkup.examples[0] has changed body Service $w.CustomElement property seoMarkup.examples[0] has changed extra.description Service $w.CustomElement operation on has changed description Service $w.CustomElement operation on.examples[0] has changed body Service $w.CustomElement operation on.examples[0] has changed extra.description Service $w.CustomElement operation setAttribute has changed param key doc Service $w.CustomElement operation setAttribute.examples[0] has changed body Service $w.CustomElement operation setAttribute.examples[0] has changed extra.description
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (37))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (612))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (651))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (690))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (727))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (26))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (62))
Mixin $w.DisabledMixin not found (AddressInput.js (62))
Mixin $w.RequiredMixin not found (AddressInput.js (62))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (62))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (62))
Mixin $w.FocusMixin not found (AddressInput.js (62))
Mixin $w.ClickableMixin not found (AddressInput.js (62))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (587))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (626))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (665))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (702))
Mixin $w.Element not found (MusicPlayer.js (9))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (9))
Mixin $w.Element not found (Captcha.js (8))
Mixin $w.FocusMixin not found (Captcha.js (8))
Mixin $w.HiddenCollapsedMixin not found (Captcha.js (8))
Property style has an unknown type $w.Style (ProgressBar.js (42))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
Mixin $w.Element not found (CustomElement.js (5))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (5))
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_get.es6' not found. File: VideoPlayer.js line: 511
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_set.es6' not found. File: VideoPlayer.js line: 511
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 711
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 711