DocWorks for js-wixcode-sdk - 13 changes detected, but 11 issue detected changes: Service $w.GoogleMap has a new property center Service $w.GoogleMap has a new property zoom Service $w.GoogleMap has a new property markers Service $w.HiddenMixin property isVisible has changed description Service $w.Slideshow operation onChange has changed extra.notes Service $w.StyleMixin has changed description Service wix-storage.Storage has changed summary Service wix-storage.Storage operation setItem has changed extra.notes Service wix-storage has changed summary Service wix-storage has changed description Service wix-window has a new operation copyToClipboard Service $w.HoverBox is new Service wix-events is new
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389